name: app_first
description: "Shopping App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  get: any
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  flutter_rating_stars: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_charts: ^27.1.52
  five_pointed_star: ^1.0.3
  image_picker: any
  permission_handler: ^11.3.1
  path_provider: ^2.1.4


flutter:
  uses-material-design: true
  assets:
    - assets/image/
